# Generated by Django 5.1.7 on 2025-03-21 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='child name ')),
                ('date_of_birth', models.DateField(verbose_name='Date of birth')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='child gender')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(limit_choices_to={'role': 'parent'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField(verbose_name='children height in cm')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='child weight')),
                ('age_months', models.IntegerField(editable=False, verbose_name='monthes age for child')),
                ('date', models.DateField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='measurement.child')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('haz', models.FloatField(editable=False, verbose_name='Height for Age z-score')),
                ('is_stunted', models.BooleanField(default=False, verbose_name='Is Stunted')),
                ('severity', models.CharField(max_length=50, null=True, verbose_name='Stunting Severity')),
                ('recommendation', models.TextField()),
                ('measurement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='measurement.measurement')),
            ],
        ),
        migrations.AddConstraint(
            model_name='measurement',
            constraint=models.CheckConstraint(condition=models.Q(('height__gte', 30), ('height__lte', 200)), name='height_range'),
        ),
    ]
